language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- node

os:
- linux
- osx

git:
  depth: 1

before_install:
  # package-lock.json was introduced in npm@5
- '[[ $(node -v) =~ ^v9.*$ ]] || travis_retry npm install -g npm@latest'

install:
- travis_retry npm install

script:
- (cd example && node build.js)
- npm test
